import xarray as xr
import numpy as np

def correct_temp(
    raw_path: str,
    new_path: str,
    dem_path: str,
    g: float = 9.80665,
    lapse_rate: float = 0.0065
):
    """
    Corrects the temperature of a model.
    Parameters:
    - raw_path: the path to the original model output
    - new_path: the path where you wish the postprocessed result would be
    - dem_path: the path where the DEM generated by the image_to_dem function is
    - g: surface gravity of the planet in m/s^2, defaults to Earth's 9.80665
    - lapse_rate: lapse_rate in K/m, 0.0065 by default
    """
    try:
        raw = xr.open_dataset(raw_path)
        dem = xr.open_dataset(dem_path)
    except FileNotFoundError as e:
        raise FileNotFoundError(f"Could not find dataset: {e}")

    if "grnz" not in raw or "elevation" not in dem:
        raise ValueError("Missing required variables in datasets")

    if "ta" not in raw or "tas" not in raw or "ts" not in raw:
        raise ValueError("Missing temperature variables (ta, tas, and ts)")
    
    new_lat = np.linspace(raw['lat'].values[0], raw['lat'].values[-1], dem.dims['lat'])
    new_lon = np.linspace(raw['lon'].values[0], raw['lon'].values[-1], dem.dims['lon'])
    raw = raw.interp(lat=new_lat, lon=new_lon, method="nearest")
 
    try:
        temp_correction = (dem["elevation"].values - raw["grnz"].values / g) * lapse_rate
        if np.any(np.isnan(temp_correction)):
            raise ValueError("NaNs detected in temperature correction; check input data for missing values")

        raw["ta"].values += temp_correction
        raw["tas"].values += temp_correction
        raw["ts"].values += temp_correction
        raw.to_netcdf(new_path)
    finally:
        raw.close()
        dem.close()
