import xarray as xr

def correct_precipitation(
    raw_path: str,
    new_path: str,
    dem_path: str
):    
    """
    Corrects the precipitation of a model.
    Parameters:
    - raw_path: the path to the original model output
    - new_path: the path where you wish the postprocessed result would be
    - dem_path: the path where the DEM generated by the image_to_dem function is
    """
    dem = xr.open_dataset(dem_path)
    raw = xr.open_dataset(raw_path)
